---

- name: ensure ~/prometheus/ directory exists
  become: no
  file:
    path: ~/prometheus/
    state: directory
    owner: vagrant

- name: copy prometheus conf 
  become: no
  copy:
    src: ./conf/prometheus.yml 
    dest: ~/prometheus/prometheus.yml
    mode: '0644'
    owner: vagrant

- name: start statsD 
  docker_container:
    name: statsD 
    image: prom/statsd-exporter
    command: --statsd.listen-udp="172.17.0.1:9125" --statsd.listen-tcp="" --web.listen-address="127.0.0.1:9102" # listen only to the docker bridge
    state: started
    restart: yes
    network_mode: host

- name: start prometheus 
  docker_container:
    name: prometheus
    image: prom/prometheus
    command: --web.listen-address=127.0.0.1:9090 --config.file=/etc/prometheus/prometheus.yml
    state: started
    restart: yes
    network_mode: host
    volumes:
      - /home/vagrant/prometheus/:/etc/prometheus/

- name: start grafana 
  docker_container:
    name: prometheus
    image: grafana/grafana 
    state: started
    restart: yes
    network_mode: host
    env:
      - GF_SERVER_HTTP_ADDR=127.0.0.1
      - GF_SERVER_HTTP_PORT=3000
