---

- name: ensure ~/prometheus/ directory exists
  become: no
  file:
    path: ~/prometheus/
    state: directory
    owner: vagrant

- name: copy prometheus conf 
  become: no
  copy:
    src: ./conf/prometheus.yml 
    dest: ~/prometheus/prometheus.yml
    mode: '0644'
    owner: vagrant

- name: add prometheus service definition 
  become: yes
  copy:
    src: ../../../../files/prometheus.hcl
    dest: /etc/consul.d/prometheus.hcl
    mode: '0640'
    owner: vagrant

- name: reload consul 
  shell: consul reload

- name: start prometheus proxy 
  docker_container:
    name: prometheus_proxy
    image: err0r500/consul-envoy
    command: --sidecar-for prometheus --http-addr 127.0.0.1:8500 --grpc-addr 127.0.0.1:8502
    auto_remove: true
    state: started
    network_mode: host
    restart: yes

- name: start prometheus 
  docker_container:
    name: prometheus
    image: prom/prometheus
    command: --web.listen-address=127.0.0.1:9090 --config.file=/etc/prometheus/prometheus.yml
    state: started
    restart: yes
    network_mode: host
    volumes:
      - /home/vagrant/prometheus/:/etc/prometheus/

- name: start grafana 
  docker_container:
    name: grafana
    image: grafana/grafana 
    state: started
    restart: yes
    network_mode: host
    env:
      GF_SERVER_HTTP_ADDR: "127.0.0.1"
      GF_SERVER_HTTP_PORT: "3000"
