---

- name: add caller-canary service definition 
  become: yes
  copy:
    src: ../../../../files/caller-canary.hcl
    dest: /etc/consul.d/caller-canary.hcl
    mode: '0640'
    owner: vagrant
  when: inventory_hostname == 'worker-1'

- name: reload consul 
  shell: consul reload
  when: inventory_hostname == 'worker-1'
  
- name: start caller_canary proxy 
  docker_container:
    name: caller_canary_proxy
    image: err0r500/consul-envoy
    command: --sidecar-for caller-canary --http-addr 172.17.0.1:8500 --grpc-addr 172.17.0.1:8502
    auto_remove: true
    state: started
    restart: yes
    published_ports:
      - "21001:21001"
  when: inventory_hostname == 'worker-1'

- name: start caller_canary 
  docker_container:
    name: caller_canary
    image: amouat/network-utils
    command: python -m SimpleHTTPServer 9000
    state: started
    restart: yes
    network_mode: "container:caller_canary_proxy"
  when: inventory_hostname == 'worker-1'
