---

- name: add echo2 service definition 
  become: yes
  copy:
    src: ../../../../files/echo2.hcl
    dest: /etc/consul.d/echo2.hcl
    mode: '0640'
    owner: vagrant
  when: inventory_hostname == 'worker-0'

- name: reload consul 
  shell: consul reload
  when: inventory_hostname == 'worker-0'
  
- name: start echo2 proxy 
  docker_container:
    name: echo2_proxy
    image: err0r500/consul-envoy
    command: --sidecar-for echo2 --http-addr 172.17.0.1:8500 --grpc-addr 172.17.0.1:8502
    auto_remove: true
    state: started
    restart: yes
    published_ports:
      - "20001:20001"
  when: inventory_hostname == 'worker-0'

- name: start echo2
  docker_container:
    name: echo2
    image: hashicorp/http-echo 
    command: -text="version 2 hello from the new echo server" 
    state: started
    restart: yes
    network_mode: "container:echo2_proxy"
  when: inventory_hostname == 'worker-0'
