---

- name: apply_defaults
  import_tasks: apply-defaults.yml 

# statsd must be running before proxies start (otherwise they won't send traffic on it)
- name: statsd
  import_tasks: statsd.yml

- name: echo
  import_tasks: echo.yml

- name: echo2
  import_tasks: echo2.yml

- name: caller
  import_tasks: caller.yml

- name: caller_canary
  import_tasks: caller-canary.yml

- name: chaos
  import_tasks: chaos.yml

