---

- name: add statsd service definition 
  become: yes
  copy:
    src: ../../../../files/statsd.hcl
    dest: /etc/consul.d/statsd.hcl
    mode: '0640'
    owner: vagrant

- name: reload consul 
  shell: consul reload

- name: start statsd proxy 
  docker_container:
    name: statsd_proxy
    image: err0r500/consul-envoy
    command: --sidecar-for statsd --http-addr 127.0.0.1:8500 --grpc-addr 127.0.0.1:8502
    auto_remove: true
    state: started
    restart: yes
    network_mode: host

- name: start statsD 
  docker_container:
    name: statsD 
    image: prom/statsd-exporter
    command: --statsd.listen-udp="172.17.0.1:9125" --statsd.listen-tcp="" --web.listen-address="127.0.0.1:9102" # listen only to the docker bridge and allow prometheus to pull through the proxy
    state: started
    restart: yes
    network_mode: host
