---

- name: install docker on clients
  hosts: workers
  become: yes
  roles:
    - docker-install

- name: install consul
  hosts: all
  order: sorted
  become: yes
  roles:
    - consul-install

- name: start containers 
  hosts: workers
  become: yes
  roles:
    - containers
