global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'prometheus-stack-monitor'

scrape_configs:
  - job_name: 'envoy-metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets: ['127.0.0.1:2345'] # statsD through consul connect exposed metrics
        labels:
          group: 'services'
