global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'prometheus-stack-monitor'

scrape_configs:
  - job_name: 'envoy-metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets: ['172.16.1.11:9102'] # statsD exposed metrics
        labels:
          group: 'services-worker-1'
